### ISSUE TITLE
The video in a post page has overflow 

### ISSUE THREAD

**Issue by abdolmajidbn** [edrisranjbar/JetCode#10]
I think  iframe youtube
For example css3 post
You should be set width 100% of parent

**Comment by edrisranjbar** [comment]
Hi @abdolmajidbn.
thanks for your interest in contribution in this repository. I checked the issue and I figured out that this is a front and problem that we can solve with setting the `max-width` of the iframe tags inside post page to 100%.

**this will fix the issue**

**Comment by abdolmajidbn** [comment]
done
