### ISSUE TITLE
In some posts in mobile there is overflow text

### ISSUE THREAD

**Issue by abdolmajidbn** [edrisranjbar/JetCode#4]
For example (آموزش ساخت ماشین حساب ساده با پایتون)

**Comment by edrisranjbar** [comment]
hey thank you for giving feedback 👍
the solution to this issue is very easy, we just need to set the max with the elements inside the post page.
like: `.post *{max-width:100%;}`

**Comment by abdolmajidbn** [comment]
That was the problem The <pre> tag doesn’t support wrapping, by default.
I fixed it and because the text was English, I changed the direction and text-align
done

**Comment by abdolmajidbn** [comment]
Done
